name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    # ─── start SonarQube inside the runner ────────────────────────
    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl --silent --fail http://localhost:9000/api/server/version"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for SonarQube to be ready
        run: |
          until curl --silent --fail http://localhost:9000/api/server/version; do
            echo "⏳ waiting on SonarQube…"
            sleep 5
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=try
            -Dsonar.sources=.
        env:
          SONAR_HOST_URL:    http://localhost:9000
          SONARQUBE_TOKEN:   ${{ secrets.SONARQUBE_TOKEN }}
